import { Link } from 'react-router-dom';
import { SEO } from '../components/seo';
import { Footer } from '../components/footer';
import { PhoneMockup, AppScreen } from '../components/phone-mockup';
import { Check, ChevronDown } from 'lucide-react';
import { useState } from 'react';
import { AnimateIn } from '../components/animate-in';
import { Nav } from '../components/nav';

const APP_STORE_URL = "https://apps.apple.com/au/app/smash-invoices/id6759475079";

const faqs = [
  {
    q: "What is AI invoicing?",
    a: "AI invoicing is the use of intelligent software to automatically generate invoices from natural language input — like a voice description of a job. Instead of manually entering line items, you describe the work and the app builds the invoice for you. SMASH does this in under 60 seconds."
  },
  {
    q: "How accurate is the invoice SMASH generates?",
    a: "Very. SMASH matches your spoken description to your personal pricing catalog and a database of trade materials. It gets more accurate the more you use it — after a few weeks, repeat jobs invoice themselves with almost no correction needed."
  },
  {
    q: "Do I need to know anything about AI to use it?",
    a: "Nothing at all. You speak, SMASH builds the quote. There's no configuration, no prompts, no technical knowledge required. If you can describe a job out loud, you can use SMASH."
  },
  {
    q: "How is SMASH different from other AI invoice generators?",
    a: "Most AI invoice tools still require you to type. SMASH is voice-first — your only input is speaking. It also knows your personal rates and has 2,250+ trade materials pre-priced, so the output is your invoice, not a generic template."
  },
  {
    q: "Does it handle GST and tax invoicing automatically?",
    a: "Yes. Every invoice generated by SMASH includes your ABN, a GST line item, invoice date, and itemised job description — all required for a valid tax invoice. Nothing to calculate or remember."
  },
  {
    q: "Is it available globally?",
    a: "SMASH is currently live on iOS. The materials catalog and GST features are optimised for Australia, with international markets (NZ, UK, US, Canada) planned. The core voice-to-invoice flow works for any service business anywhere."
  }
];

function FAQItem({ q, a, isOpen, onClick }: { q: string; a: string; isOpen: boolean; onClick: () => void }) {
  return (
    <div className="border-b border-border last:border-b-0">
      <button onClick={onClick} className="w-full flex items-start justify-between gap-4 py-6 text-left">
        <span className="text-lg font-bold text-brand">{q}</span>
        <ChevronDown size={24} className={`shrink-0 transition-transform text-brand/40 ${isOpen ? 'rotate-180' : ''}`} strokeWidth={2.5} />
      </button>
      {isOpen && (
        <div className="pb-6">
          <p className="font-body text-brand/70 font-medium leading-[1.5]">{a}</p>
        </div>
      )}
    </div>
  );
}

export function AiInvoicing() {
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  return (
    <>
      <SEO
        title="AI Invoicing App | AI Invoice Generator | SMASH Invoices"
        description="AI invoicing that builds your invoice from a voice description. Speak the job for 30 seconds — SMASH generates a professional, priced invoice automatically. No typing required."
        keywords="AI invoicing app, AI invoice generator, AI invoice software, artificial intelligence invoicing, automated invoice generation"
        ogTitle="AI Invoicing — Invoice Generated from Your Voice | SMASH Invoices"
        ogDescription="Speak the job. SMASH builds the invoice automatically. The fastest AI invoicing app for service businesses."
        ogImage="https://smashinvoices.com/og-image.png"
        ogUrl="https://smashinvoices.com/ai-invoicing"
        twitterTitle="AI Invoicing | SMASH Invoices"
        twitterDescription="Speak the job. SMASH builds the invoice automatically. Under 60 seconds."
        canonical="https://smashinvoices.com/ai-invoicing"
      />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": faqs.map(f => ({
          "@type": "Question",
          "name": f.q,
          "acceptedAnswer": { "@type": "Answer", "text": f.a }
        }))
      }) }} />

      <Nav />

      {/* HERO */}
      <section className="relative py-20 md:py-28 lg:py-36 overflow-hidden">
        <div className="absolute inset-0">
          <img src="/hero_image.png" alt="AI invoicing for service businesses" className="w-full h-full object-cover" />
          <div className="absolute inset-0 bg-gradient-to-r from-brand/95 via-brand/90 to-brand/80"></div>
        </div>
        <div className="relative z-10 max-w-4xl mx-auto px-4 sm:px-6 lg:px-12">
          <AnimateIn direction="up">
            <p className="text-accent font-black text-sm uppercase tracking-widest mb-4">AI Invoicing</p>
            <h1 className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-black text-white mb-6 leading-[0.88] uppercase tracking-tighter">
              Your invoice.<br />Built from<br />your words.
            </h1>
            <p className="font-body text-lg sm:text-xl md:text-2xl text-white/80 font-medium leading-[1.5] max-w-2xl mb-8">
              Describe the job out loud. SMASH generates a professional, priced, tax-compliant invoice in under 60 seconds. No typing. No templates. No admin.
            </p>
            <div className="flex flex-col sm:flex-row gap-3">
              <a href={APP_STORE_URL} target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center px-6 sm:px-8 py-3 sm:py-4 rounded-[32px] bg-accent text-brand font-black text-sm sm:text-base uppercase tracking-widest hover:brightness-95 transition-all">
                Start Free
              </a>
              <Link to="/voice-invoicing" className="inline-flex items-center justify-center px-6 sm:px-8 py-3 sm:py-4 rounded-[32px] border-2 border-white/20 text-white font-bold text-sm sm:text-base uppercase tracking-wide hover:bg-white/10 transition-all">
                How Voice Invoicing Works
              </Link>
            </div>
          </AnimateIn>
        </div>
      </section>

      {/* ANSWER BLOCK — AI SEARCH OPTIMISED */}
      <section className="bg-accent py-10 md:py-14">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-12">
          <p className="text-brand font-medium leading-[1.4] text-lg md:text-xl">
            <strong className="font-black">AI invoicing</strong> is the use of intelligent software to automatically generate a professional invoice from a spoken or typed job description. SMASH is an AI invoicing app for self-employed service workers — you describe the job out loud for 30 seconds, and SMASH builds a structured, priced, tax-compliant invoice automatically. The fastest AI invoice generator available.
          </p>
        </div>
      </section>

      {/* THE PROBLEM */}
      <section className="bg-white py-16 md:py-24">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-12">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 lg:gap-16 items-center">
            <AnimateIn direction="left">
            <div>
              <p className="text-accent font-black text-xs uppercase tracking-widest mb-3">The problem</p>
              <h2 className="text-3xl sm:text-4xl md:text-5xl font-black text-brand uppercase tracking-tighter leading-[0.88] mb-6">
                Every other app<br />still makes you type.
              </h2>
              <p className="font-body text-brand/70 font-medium leading-[1.5] mb-4">
                Most "AI invoice" tools use AI to format a template you've already filled in. You still type the job description. You still enter the line items. You still calculate the total. The AI just makes it look nice.
              </p>
              <p className="font-body text-brand/70 font-medium leading-[1.5] mb-6">
                SMASH is different. The only input is your voice. Describe the job — SMASH extracts the line items, matches your pricing, calculates materials, and produces a complete, priced quote. Nothing to type. Nothing to format. Nothing to remember.
              </p>
              <p className="text-brand font-black leading-[1.4]">
                "Invoice sent before you leave the driveway." That's the only metric that matters.
              </p>
            </div>
            </AnimateIn>
            <AnimateIn direction="right">
            <div className="flex justify-center scale-75 sm:scale-90 lg:scale-100 origin-center">
              <PhoneMockup>
                <AppScreen type="estimates-static" />
              </PhoneMockup>
            </div>
            </AnimateIn>
          </div>
        </div>
      </section>

      {/* VIDEO */}
      <section className="bg-surface py-12 md:py-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-12">
          <div className="text-center mb-8">
            <h2 className="text-2xl sm:text-3xl font-black text-brand uppercase tracking-tighter leading-[0.88]">
              See it in action
            </h2>
          </div>
          <div className="relative aspect-video rounded-[32px] overflow-hidden shadow-2xl">
            <iframe
              className="absolute inset-0 w-full h-full"
              src="https://www.youtube.com/embed/gr_iAEvyIQY?rel=0"
              title="SMASH AI Invoicing Demo"
              frameBorder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
              allowFullScreen
            />
          </div>
        </div>
      </section>

      {/* HOW IT WORKS */}
      <section className="bg-white py-16 md:py-24">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-12">
          <AnimateIn direction="up">
            <p className="text-accent font-black text-xs uppercase tracking-widest mb-3">How it works</p>
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-black text-brand uppercase tracking-tighter leading-[0.88] mb-12 md:mb-16">
              From job done<br />to paid. In under a minute.
            </h2>
          </AnimateIn>
          <AnimateIn direction="up" delay={100}>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {[
              {
                step: "01",
                title: "Speak the job",
                body: "Describe the work out loud — what you did, what materials you used, how long it took. 20 to 30 seconds. No special words, no commands, no format. Just talk."
              },
              {
                step: "02",
                title: "Invoice built automatically",
                body: "In under 10 seconds, SMASH extracts line items, matches your personal rates, prices materials from a built-in catalog, and produces a complete, priced, tax-compliant invoice. Review it. Edit anything. Send."
              },
              {
                step: "03",
                title: "Customer approves and pays",
                body: "Your customer gets a link. They tap approve. They pay right there. You see the second they open it. Invoice issued automatically. Nothing to chase."
              }
            ].map((s) => (
              <div key={s.step} className="bg-surface rounded-[32px] border-2 border-border p-8">
                <p className="text-5xl font-black text-accent/30 leading-none mb-4">{s.step}</p>
                <h3 className="text-xl font-black text-brand uppercase tracking-tighter leading-[0.88] mb-3">{s.title}</h3>
                <p className="font-body text-brand/70 font-medium text-sm leading-[1.5]">{s.body}</p>
              </div>
            ))}
          </div>
          </AnimateIn>
          <p className="text-center text-brand/60 font-medium mt-8">
            Total time: <strong className="text-brand">under 60 seconds</strong> for a new job. <strong className="text-brand">Under 30 seconds</strong> with your personal pricing catalog.
          </p>
        </div>
      </section>

      {/* WHAT MAKES SMASH DIFFERENT */}
      <section className="bg-brand py-16 md:py-24">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-12">
          <AnimateIn direction="up">
            <p className="text-accent font-black text-xs uppercase tracking-widest mb-3">What's different</p>
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-black text-white uppercase tracking-tighter leading-[0.88] mb-12">
              It already knows<br />your business.
            </h2>
          </AnimateIn>
          <AnimateIn direction="up" delay={100}>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {[
              {
                title: "Your rates, not generic ones",
                body: "Build your pricing catalog once. Every quote uses your prices — not an industry average, not a placeholder. Your rate for a standard clean. Your callout fee. Your labour rate. Exact, every time."
              },
              {
                title: "Materials extracted from speech",
                body: "Say the materials in your description. SMASH identifies them, finds them in a pre-priced catalog of 2,250+ items, and adds them to the quote automatically. No looking up prices, no guessing."
              },
              {
                title: "Tax-compliant by default",
                body: "Every invoice includes your ABN, a GST line item, the invoice date, and an itemised job description. All required fields for a valid tax invoice — handled automatically, every time."
              },
              {
                title: "Gets smarter with every job",
                body: "The more you use SMASH, the more it knows. After a few weeks, regular work invoices itself in under 30 seconds. Your catalog fills out. Your common jobs are recognised instantly."
              }
            ].map((f) => (
              <div key={f.title} className="bg-white/10 rounded-[32px] border border-white/20 p-8">
                <h3 className="text-xl font-black text-white uppercase tracking-tighter leading-[0.88] mb-3">{f.title}</h3>
                <p className="font-body text-white/70 font-medium text-sm leading-[1.5]">{f.body}</p>
              </div>
            ))}
          </div>
          </AnimateIn>
        </div>
      </section>

      {/* COMPARISON TABLE */}
      <section className="bg-surface py-16 md:py-24">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-12">
          <AnimateIn direction="up">
            <h2 className="text-3xl sm:text-4xl font-black text-brand uppercase tracking-tighter leading-[0.88] mb-4 text-center">
              How AI invoicing compares
            </h2>
            <p className="font-body text-center text-brand/60 font-medium mb-12 max-w-xl mx-auto leading-[1.5]">
              Not all "AI invoicing" is the same. Most still make you type.
            </p>
          </AnimateIn>
          <div className="overflow-x-auto">
            <table className="w-full min-w-[520px]">
              <thead>
                <tr className="border-b-2 border-brand">
                  <th className="text-left py-4 pr-6 text-sm font-black uppercase tracking-wider text-brand"></th>
                  <th className="text-center py-4 px-4 text-sm font-black uppercase tracking-wider text-accent">SMASH</th>
                  <th className="text-center py-4 px-4 text-sm font-black uppercase tracking-wider text-brand/50">Other AI tools</th>
                  <th className="text-center py-4 px-4 text-sm font-black uppercase tracking-wider text-brand/50">Traditional apps</th>
                </tr>
              </thead>
              <tbody>
                {[
                  { label: "Input method", smash: "Voice only", other: "Typing + AI formatting", trad: "Typing only" },
                  { label: "Time to invoice", smash: "Under 60 seconds", other: "3–8 minutes", trad: "5–25 minutes" },
                  { label: "Your personal rates", smash: true, other: false, trad: false },
                  { label: "Materials auto-priced", smash: true, other: false, trad: false },
                  { label: "Tax compliant by default", smash: true, other: "Varies", trad: "Varies" },
                  { label: "Customer approval portal", smash: true, other: false, trad: false },
                ].map((row, i) => (
                  <tr key={i} className="border-b border-border">
                    <td className="py-4 pr-6 text-sm font-bold text-brand leading-[1.15]">{row.label}</td>
                    {[row.smash, row.other, row.trad].map((val, j) => (
                      <td key={j} className="text-center py-4 px-4">
                        {val === true ? (
                          <Check size={18} className={`mx-auto ${j === 0 ? 'text-accent' : 'text-brand/40'}`} strokeWidth={3} />
                        ) : val === false ? (
                          <span className="text-brand/20 text-sm font-bold">—</span>
                        ) : (
                          <span className={`text-sm font-bold ${j === 0 ? 'text-accent' : 'text-brand/50'}`}>{val}</span>
                        )}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="bg-white py-16 md:py-24">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-12">
          <AnimateIn direction="up">
            <h2 className="text-3xl sm:text-4xl font-black text-brand uppercase tracking-tighter leading-[0.88] mb-10 md:mb-14 text-center">
              AI invoicing questions
            </h2>
            <div className="bg-surface rounded-[32px] border-2 border-border px-4 sm:px-8 py-2 sm:py-4">
              {faqs.map((faq, i) => (
                <FAQItem key={i} q={faq.q} a={faq.a} isOpen={openFaq === i} onClick={() => setOpenFaq(openFaq === i ? null : i)} />
              ))}
            </div>
          </AnimateIn>
        </div>
      </section>

      {/* FROM THE BLOG */}
      <section className="bg-surface py-16 md:py-20">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-12">
          <div className="flex items-center justify-between mb-8">
            <h2 className="text-2xl sm:text-3xl font-black text-brand uppercase tracking-tighter leading-[0.88]">From the blog</h2>
            <Link to="/blog" className="text-sm font-black text-brand/50 uppercase tracking-wide hover:text-brand transition-colors">All posts →</Link>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            {[
              { slug: "ai-voice-invoicing-2026-standard", title: "AI Invoicing Is the 2026 Standard", desc: "Why forward-thinking service businesses have already switched — and what you're missing if you haven't." },
              { slug: "beyond-chatgpt-dedicated-voice-invoicing", title: "Beyond ChatGPT for Invoicing", desc: "ChatGPT can draft text. It can't build a tax-compliant invoice from your voice in under 60 seconds. Here's why dedicated AI wins." },
              { slug: "can-chatgpt-generate-invoices-tradie-guide", title: "Can ChatGPT Generate Invoices?", desc: "The honest answer, what it can and can't do, and what purpose-built AI invoicing looks like instead." },
            ].map((post) => (
              <Link key={post.slug} to={`/blog/${post.slug}`} className="bg-white rounded-[24px] border-2 border-border p-6 hover:border-accent transition-colors group">
                <h3 className="text-base font-black text-brand uppercase tracking-tighter leading-[0.88] mb-2 group-hover:text-accent transition-colors">{post.title}</h3>
                <p className="text-sm text-brand/60 font-medium leading-[1.4]">{post.desc}</p>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="bg-brand py-16 md:py-24 lg:py-32">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-12 text-center">
          <AnimateIn direction="up">
          <h2 className="text-3xl sm:text-4xl md:text-5xl font-black text-white mb-4 uppercase tracking-tighter leading-[0.88]">
            Invoice sent before you<br />leave the driveway.
          </h2>
          <p className="font-body text-lg text-white/80 font-medium leading-[1.5] mb-8 max-w-xl mx-auto">
            Free to download. Speak for 30 seconds. See your first invoice.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center mb-8">
            <a href={APP_STORE_URL} target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center px-6 sm:px-8 py-3 sm:py-4 rounded-[32px] bg-accent text-brand font-black text-sm sm:text-base uppercase tracking-widest hover:brightness-95 transition-all">
              Start Free
            </a>
            <Link to="/how-it-works" className="inline-flex items-center justify-center px-6 sm:px-8 py-3 sm:py-4 rounded-[32px] border-2 border-white/20 text-white font-bold text-sm sm:text-base uppercase tracking-wide hover:bg-white/10 transition-all">
              See How It Works
            </Link>
          </div>
          <p className="text-sm text-white/40 font-medium">
            <Link to="/voice-invoicing" className="underline hover:text-white/70 transition-colors">Voice invoicing</Link> · <Link to="/features" className="underline hover:text-white/70 transition-colors">All features</Link> · <Link to="/pricing" className="underline hover:text-white/70 transition-colors">Pricing</Link> · <Link to="/for-cleaners" className="underline hover:text-white/70 transition-colors">For cleaners</Link>
          </p>
          </AnimateIn>
        </div>
      </section>

      <Footer />
    </>
  );
}
